#pragma once

#include <stdint.h>
#include <stddef.h>
#include <limine.h>
#include <libhydrix/hcon/console.h>
#include <libhydrix/hdebug/serial.h>
#include <libhydrix/hdisplay/hdisplay.h>
#include <libhydrix/hgl/color.h>
#include <libhydrix/hgl/fonts.h>
#include <libhydrix/hgl/graphics.h>
#include <libhydrix/hinteger/hinteger.h>
#include <libhydrix/hio/io.h>
#include <libhydrix/hkey/keyboard.h>
#include <libhydrix/hlow/cpu/cpu.h>
#include <libhydrix/hlow/fpu/fpu.h>
#include <libhydrix/hlow/gdt/gdt.h>
#include <libhydrix/hlow/idt/idt.h>
#include <libhydrix/hlow/idt/isr.h>
#include <libhydrix/hlow/pic/pic.h>
#include <libhydrix/hlow/pit/pit.h>
#include <libhydrix/hmath/floatmath.h>
#include <libhydrix/hmath/higherbitmath.h>
#include <libhydrix/hmath/intmath.h>
#include <libhydrix/hmem/smem/heap.h>
#include <libhydrix/hmem/smem/smem.h>
#include <libhydrix/hmouse/mouse.h>
#include <libhydrix/hrand/rand.h>
#include <libhydrix/hstring/string.h>
#include <libhydrix/hsyscall/syscall.h>
#include <libhydrix/sdefs.h>
#include <libhydrix/htime/htime.h>
#include <libhydrix/hlow/pci/pci.h>
#include <libhydrix/hgl/image.h>
#include <libhydrix/hlow/cpu/cpuchecks.h>
